pagemachine/searchable

Classes/Utility/TsfeUtility.php
Flushing the internal runtime caches is necessary here since `HTTP_HOST` is already retrieved once (as `NULL`) early by `PageRenderer::addRequireJsConfiguration()`.
=> Inject fake HTTP host for indexing

Classes/DataCollector/PagesDataCollector.php, Tests/Functional/AbstractElasticsearchTest.php, Tests/Functional/Service/IndexingServiceTest.php
It does not make much sense to load such pages only to skip them
immediately afterwards.
=> Skip pages with "no_search" via query

Classes/Command/Index/UpdateFullCommand.php, Classes/Command/Index/UpdatePartialCommand.php, Classes/Service/IndexingService.php
The scheduler tasks are stored with an empty string as value for "type"
which is then passed through to the indexing service. To ensure all
types are processed in this case, normalize everything to use an empty
string by default.
=> Normalize index type

Resources/Public/JavaScript/searchable.js
The search logic happens in a timer, if a search is too slow than the configured delay, the same search will be performed again.
This leads to the same results being appended again and again until the situation normalizes over time.
To avoid this, we directly update the last term and page every time the search is processed instead of doing this after the search results where retrieved.
=> Prevent result duplication on slow search

Classes/DataCollector/Utility/OverlayUtility.php, Tests/Functional/AbstractElasticsearchTest.php, Tests/Functional/Fixtures/Extensions/unlocalized_table_test/Configuration/TCA/tx_unlocalizedtabletest_unlocalizedtable.php, Tests/Functional/Fixtures/Extensions/unlocalized_table_test/composer.json, Tests/Functional/Fixtures/Extensions/unlocalized_table_test/ext_emconf.php, Tests/Functional/Fixtures/Extensions/unlocalized_table_test/ext_tables.sql, Tests/Functional/Service/IndexingServiceTest.php
Tables without localization (ctrl/languageField in TCA) are perfectly fine. In this case we should index records of the default language and skip processing for other languages.
=> Index unlocalized tables

composer.json
Reverts pagemachine/searchable#101
This was accidentally automerged when PR checks/requirements where adjusted for https://github.com/pagemachine/searchable/pull/106
=> Revert "[TASK] Update sclable/xml-lint (^0.5.0 => ^0.6.0)"

Classes/DataCollector/Utility/OverlayUtility.php, Classes/Indexer/Indexer.php, Classes/Service/IndexingService.php, Classes/Utility/TsfeUtility.php, Tests/Functional/AbstractElasticsearchTest.php, Tests/Functional/Query/SearchQueryTest.php, Tests/Functional/Service/IndexingServiceTest.php, doc/getting-started.md
=> Support site and site languages per indexer

composer.json
This is obsolete since TYPO3v11.
=> Drop obsolete functional test environment setup

.github/workflows/ci.yml
See https://github.com/pagemachine/searchable/pull/92
=> Drop obsolete CI matrix TYPO3v10 excludes

composer.json
Reverts pagemachine/searchable#117
This was merged when CI was broken and no required checks were active.
=> Revert "[TASK] Update typo3/testing-framework (^7.0 => ^8.0)"

Classes/Preview/FluidPreviewRenderer.php
This was added with TYPO3v12 but for now we keep supporting TYPO3v11.
See https://github.com/pagemachine/searchable/pull/126
=> Verify request can be set on Fluid view

Classes/Command/Index/AbstractIndexCommand.php
In TYPO3v12 opening the Scheduler module which contains Searchable indexing tasks did lead to a BE logout.
The reason for this was the "initializeUserSessionManager()" call as performed for all indexing commands. Commands registered as Scheduler tasks are instantiated once to collect them for display in the module. Due to said session manager initialization the existing BE user session was replaced with an anonymous one, effectively resulting in a BE logout.
However, we cannot drop this call completely since it is necessary for the clipboard access in "TYPO3\CMS\Backend\Form\FormDataProvider"; this fails with a BE user without initialized session.
So for now we avoid this issue by checking for the type of the BE user. We now only initialize the user session manager for CLI; in …
=> Prevent BE logout in Scheduler module

Classes/DataCollector/PagesDataCollector.php
The list of page UIDs processed here is the result of a ES query where the values are numeric strings. Since TYPO3v12 the RootlineUtility uses native types and now strictly expects an integer.
See https://github.com/TYPO3/typo3/commit/91462d7bccf3325870a04fba9d5ae4904c4219fe
=> Ensure integer type for UID passed to RootlineUtility

rector.php
This is not loaded anymore with PHP > 7.4.
=> Remove obsolete AddLiteralSeparatorToNumberRector skip

Classes/DataCollector/PagesDataCollector.php, Tests/Functional/Service/IndexingServiceTest.php, Tests/Unit/DataCollector/PagesDataCollectorTest.php, doc/configuration/data-collector.md
The functional test also covers the other two transient doktypes.
=> Index pages within "Link to External URL" (doktype=3) pages

docker-compose.yml
This guarantees these services are up and running.
=> Add healthchecks to mysql/elasticsearch Compose services

Classes/Command/Index/AbstractIndexCommand.php, phpstan-baseline.neon
The "visibility" aspect set up by the TYPO3 CommandApplication includes hidden content (and thus records) by default. This can be seen especially when using the Extbase persistence during the indexing process. Related objects ignore any enable fields and are loaded unconditionally.
This whole topic very likely needs further investigation and additional restrictions (e.g. skip hidden pages and scheduled records) but left for another change.
=> Skip hidden content/records on indexing

Configuration/Backend/Modules.php
The backend module does not interact with the page tree, so it doesn't make sense to have it displayed here.
=> Remove page tree from BE module

Classes/Controller/BackendController.php
This ensures that one gets at least a successful response instead of an error due to the undefined "typo3" index.
=> Use first index in BE "request" action

ext_localconf.php
This plugin is stateless and not affected e.g. by the search term. So we can actually enable caching for this plugin.
=> Enable caching for "Live search bar" plugin
